# Generated by Django 2.1 on 2018-09-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0003_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
