# Generated by Django 2.1 on 2018-09-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0004_wallet_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
